import { useEffect, useRef, useState } from 'react';
import type { ReactNode } from 'react';
import { Badge, Button, Card, Empty, Facts, Field, Head, Icon, Loading, Notice, RouteLink, Timeline } from './components';
import { useApp } from './context';
import { cases, deliveryLabels, devices, driverLocations, observedAt } from './fixtures';
import { canReceive, cancelCommand, commandLabel, commandSteps, executionLabels, newCommand, notificationSummary, resolveCommand, startCommand } from './model';
import type { Command, Reply } from './model';
import { ParkingMap } from './ParkingMap';

function DataRegion({ children, empty, unavailable = false }: { children: ReactNode; empty?: string; unavailable?: boolean }) {
  const { state, setState } = useApp();
  if (state.mode === 'loading') return <Loading/>;
  if (state.mode === 'error' && !unavailable) return <div className="card-body"><Notice title="정보를 불러올 수 없어요."/><Button onClick={() => setState(s => ({ ...s, mode: 'normal' }))}>다시 보기</Button></div>;
  if (state.mode === 'empty' && empty) return <Empty title={empty}/>;
  return <>{children}</>;
}
function incidentStatus(id: string, fallback: string) { return id === 'aisle' ? null : fallback; }
function CaseRow({ item }: { item: typeof cases[number] }) {
  const { state, setState, go, route } = useApp();
  const resolved = item.id === 'aisle' ? state.followup === 'recovered' : item.tone === 'green';
  return <button className="list-item clickable" onClick={() => { setState(s => ({ ...s, returnCase: route })); go(`/owner/incidents/${item.id}`); }}><span className={`list-dot ${resolved ? 'green' : ''}`}/><span className="list-text"><strong>{item.title}</strong><small>{item.place} · {item.time}</small><Badge tone={resolved ? 'green' : item.tone}>{incidentStatus(item.id, item.status) || (resolved ? '해결' : state.followup === 'insufficient' ? '보류' : item.status)}</Badge></span><span className="list-arrow" aria-hidden="true">↗</span></button>;
}
export function Monitor() {
  const { state, setState, go, open } = useApp(); const items = cases.filter(c => c.tone !== 'green' && !(c.id === 'aisle' && state.followup === 'recovered'));
  return <><Head title="관제 현황" action={<RouteLink to="/owner/commands" className="btn primary">운영 요청</RouteLink>}/><div className="stats">{[['관측 차량', state.mode === 'empty' ? '—' : '2'], ['진행 사건', state.mode === 'empty' ? '0' : String(items.length)], ['확인 필요', state.mode === 'empty' ? '0' : '2']].map(([name, value], i) => <div className="stat" key={name}><span>{name}</span><strong className={i === 1 ? 'accent' : ''}>{value}</strong></div>)}<div className="stat"><span>입차 정책</span><strong className="policy-value">허용</strong><small>게이트: 열림</small></div></div>
    <div className="grid two"><Card title="주차장 지도" action={<Badge>마지막 관측</Badge>} body={false} footer={`관측: ${observedAt}`}><DataRegion empty="관측 없음"><ParkingMap selected={state.selectedCar} onSelect={id => setState(s => ({ ...s, selectedCar: id }))} onCase={() => { setState(s => ({ ...s, returnCase: '/owner/monitor' })); go('/owner/incidents/aisle'); }} stale={['stale', 'offline'].includes(state.mode)}/></DataRegion></Card><div className="stack"><Card title="진행 사건" action={<RouteLink to="/owner/incidents" className="btn-link">전체 보기</RouteLink>} body={false}><DataRegion empty="진행 사건 없음">{items.map(c => <CaseRow key={c.id} item={c}/>)}</DataRegion></Card><Card title="AI 처리" body={false}><div className="mini-summary"><span>차주 응답: {state.responses.move || '응답 대기'}</span><Badge tone="amber">{state.followup === 'recovered' ? '해결 확인' : '후속 확인'}</Badge></div><div className="card-body"><p className="muted followup-note">{notificationSummary(state)}</p></div></Card></div></div>
    <div className="device-grid">{Object.entries(devices).map(([id, d]) => <button className="device-tile" key={id} onClick={() => open({ type: 'device', id })}><Icon name={id === 'alarm' ? 'bell' : id}/><strong>{d.title}</strong><small>{d.subtitle} ↗</small></button>)}</div></>;
}
export function IncidentList() {
  const { state, setState } = useApp(); const filtered = cases.filter(c => state.filter === 'all' || (state.filter === 'review' ? ['확인 필요', '보류'].includes(c.id === 'aisle' ? state.followup === 'insufficient' ? '보류' : state.followup === 'recovered' ? '해결' : c.status : c.status) : state.filter === 'resolved' ? c.tone === 'green' || (c.id === 'aisle' && state.followup === 'recovered') : c.tone !== 'green' && !(c.id === 'aisle' && state.followup === 'recovered')));
  return <><Head title="사건 관리" action={<Badge>{state.mode === 'empty' ? 0 : filtered.length}건</Badge>}/><div className="filters" role="group" aria-label="사건 상태 필터">{[['all', '전체'], ['active', '진행 중'], ['review', '확인 필요·보류'], ['resolved', '해결']].map(([value, label]) => <button className="filter" key={value} aria-pressed={state.filter === value} onClick={() => setState(s => ({ ...s, filter: value }))}>{label}</button>)}</div><Card body={false}><DataRegion empty="사건 없음">{filtered.length ? filtered.map(c => <CaseRow key={c.id} item={c}/>) : <Empty title="사건 없음">다른 필터를 선택해 보세요.</Empty>}</DataRegion></Card></>;
}
export function IncidentDetail({ id }: { id: string }) {
  const { state } = useApp(); const c = cases.find(c => c.id === id); if (!c) return <Missing name="사건" to="/owner/incidents"/>;
  const related = id === 'aisle'; const summary = related ? notificationSummary(state) : c.next; const resolved = related ? state.followup === 'recovered' : c.tone === 'green';
  return <><RouteLink to={state.returnCase} className="back">이전 화면으로</RouteLink><Head title={c.title} action={<Badge tone={resolved ? 'green' : c.tone}>{resolved ? '해결' : related && state.followup === 'insufficient' ? '보류' : c.status}</Badge>}/><Notice title={summary} neutral/>
    <div className="detail-grid"><div className="stack"><Card title="사건 정보" action={<Badge>{c.type}</Badge>}><p className="incident-summary">{c.summary}</p><div className="section-gap"><Facts items={[["발생 위치", c.place], ['발생 시각', c.time], ['차주/장치 응답', related ? state.responses.move || '응답 대기' : c.response]]}/></div></Card><Card title="처리 흐름"><Timeline items={[{ title: '관측 · 영향 확인', text: `${c.place} · 통행 공간 확인` }, { title: '연락·장치 요청', text: related ? deliveryLabels[state.delivery] : id === 'risk' ? '독립 경보 확인' : '대상·허용 조치 확인' }, { title: '수신·응답', text: related ? state.responses.move || (state.deadlinePassed ? '응답 기한 경과 · 무응답' : '응답 대기') : c.response }, { title: '후속 확인', text: summary, pending: !resolved }]}/></Card></div><div className="stack"><Card title="사건 위치"><RouteLink to="/owner/monitor" className="btn full">지도 보기</RouteLink></Card>{related && <Card title="연락 결과"><Badge tone={state.delivery === 'failed' ? 'red' : state.delivery === 'unknown' ? 'amber' : ''}>{deliveryLabels[state.delivery]}</Badge>{state.delivery === 'failed' && <p className="form-note section-gap">채널 오류 · 소유자 확인 필요. 재발송하지 않았습니다.</p>}{state.delivery === 'unknown' && <p className="form-note section-gap">발송 여부 확인 전 · 중복 발송 보류</p>}</Card>}<p className="pending-features">운영 규정 근거: 연결 준비 중</p></div></div></>;
}
export function CommandPage() {
  const { state, setState, draft, editDraft, blocked, go } = useApp(); const values = draft('command', { message: '', goal: 'closing' });
  return <><Head title="AI 운영 요청"/><div className="grid equal"><Card title="새 요청"><form onSubmit={e => { e.preventDefault(); if (blocked || !values.message.trim()) return; const existing = state.commands.find(c => c.text === values.message.trim() && c.goal === values.goal && !['cancelled', 'complete', 'failed'].includes(c.phase)); const c = existing || newCommand(`preview-${crypto.randomUUID()}`, values.message, values.goal as Command['goal']); if (!existing) setState(s => ({ ...s, commands: [c, ...s.commands] })); go(`/owner/commands/${c.id}`); }}><Field label="요청 유형" as="select" input={{ value: values.goal, onChange: e => editDraft('command', 'goal', e.target.value, values) }}><option value="closing">영업 종료</option><option value="notice">구역 안내</option></Field><Field label="요청 내용" as="textarea" hint={!values.message.trim() ? '요청 내용을 입력하면 계획을 확인할 수 있습니다.' : undefined} input={{ value: values.message, maxLength: 500, placeholder: '예: 영업 종료 안내 후 신규 입차를 제한해 주세요.', onChange: e => editDraft('command', 'message', e.target.value, values) }}/><Button type="submit" variant="primary full" disabled={blocked || !values.message.trim()}>계획 보기 <Icon name="arrow"/></Button></form></Card><div className="stack"><Card title="요청 목록" body={false}><DataRegion empty="요청 없음">{state.commands.length ? state.commands.map(c => <a className="list-item clickable" href={`#/owner/commands/${c.id}`} key={c.id}><span className="list-dot"/><span className="list-text"><strong>{c.text}</strong><small>{c.goal === 'closing' ? '영업 종료' : '구역 안내'}</small><Badge tone={['partial', 'held', 'unknown'].includes(c.phase) ? 'amber' : c.phase === 'complete' ? 'green' : ''}>{commandLabel(c)}</Badge></span><span className="list-arrow">↗</span></a>) : <Empty title="요청 없음"/>}</DataRegion></Card><p className="pending-features">서버 전체 이력 · 규정 답변: 연결 준비 중</p></div></div></>;
}
export function CommandDetail({ id }: { id: string }) {
  const { state, setState, draft, editDraft, blocked, toast } = useApp(); const c = state.commands.find(c => c.id === id); const target = draft(`target:${id}`, { target: '데모 주차장 전체' });
  const phaseKey = `${c?.phase}:${c?.cancelRequested}`;
  const previousPhase = useRef(phaseKey);
  useEffect(() => { if (previousPhase.current !== phaseKey) requestAnimationFrame(() => document.querySelector<HTMLElement>('.detail-grid h2')?.focus()); previousPhase.current = phaseKey; }, [phaseKey]);
  if (!c) return <Missing name="요청" to="/owner/commands"/>;
  const modify = (update: (c: Command) => Command) => setState(s => ({ ...s, commands: s.commands.map(x => x.id === id ? update(x) : x) }));
  const phaseIndex = c.phase === 'clarify' ? 1 : c.phase === 'plan' ? 2 : 3;
  return <><RouteLink to="/owner/commands" className="back">요청 목록으로</RouteLink><Head title="운영 요청" action={<Badge tone={c.phase === 'complete' ? 'green' : ['partial', 'held', 'unknown'].includes(c.phase) ? 'amber' : c.phase === 'failed' ? 'red' : ''}>{commandLabel(c)}</Badge>}/><div className="step-labels">{['01 요청 입력', '02 대상 확인', '03 계획 검토', '04 결과 확인'].map((name, i) => <span key={name} className={phaseIndex === i ? 'active' : ''} aria-current={phaseIndex === i ? 'step' : undefined}>{name}</span>)}</div><div className="detail-grid"><Card title={c.phase === 'clarify' ? '대상 확인' : c.phase === 'plan' ? '예정 조치' : '단계별 결과'}>
    {c.phase === 'clarify' ? <form onSubmit={e => { e.preventDefault(); if (!blocked) modify(x => ({ ...x, target: target.target, phase: 'plan' })); }}><Field label="대상 범위" as="select" input={{ value: target.target, onChange: e => editDraft(`target:${id}`, 'target', e.target.value, target) }}><option>데모 주차장 전체</option><option>방송 구역 A</option><option>방송 구역 B</option></Field><Button type="submit" variant="primary" disabled={blocked}>계획 보기</Button></form> : <>
      {c.cancelRequested && <Notice title={c.steps.some(s => ['running', 'unknown'].includes(s)) ? '취소 요청 · 진행 단계 결과 확인 필요' : '미실행 단계 취소'} neutral>완료·실패한 결과는 유지됩니다.</Notice>}
      {commandSteps(c.goal).map((label, i) => <div className="plan-step" key={label}><span className="step-number">{i + 1}</span><div className="list-text"><strong>{label}</strong>{c.steps[i] === 'failed' && <small>{i === 1 ? '방송 구역 B 전달 실패' : '출차 상태 조회 실패'}</small>}{c.steps[i] === 'held' && <small>{c.phase === 'held' ? '장애물 확인 전 · 안전 조건 미충족' : '앞 단계의 결과 확인 필요'}</small>}{c.steps[i] === 'unknown' && <small>결과 확인 전 · 자동 재실행 보류</small>}</div><Badge tone={c.steps[i] === 'succeeded' ? 'green' : c.steps[i] === 'failed' ? 'red' : ['held', 'unknown'].includes(c.steps[i]) ? 'amber' : ''}>{c.phase === 'plan' ? '예정' : executionLabels[c.steps[i]]}</Badge></div>)}
      <div className="dialog-actions">{c.phase === 'plan' && <Button variant="primary" disabled={blocked} onClick={() => modify(startCommand)}>확인하고 진행</Button>}{c.phase === 'running' && !c.cancelRequested && <Button variant="primary" disabled={blocked} onClick={() => modify(x => resolveCommand(x, state.outcome))}>단계별 결과 보기</Button>}{c.cancelRequested && c.steps.some(s => ['running', 'unknown'].includes(s)) && <Button disabled={blocked} onClick={() => modify(x => cancelCommand({ ...x, steps: x.steps.map(s => s === 'running' || s === 'unknown' ? 'succeeded' : s) }))}>진행 단계 결과 확인</Button>}{c.phase === 'unknown' && !c.cancelRequested && <Button disabled={blocked} onClick={() => { modify(x => ({ ...x, phase: 'partial', steps: x.steps.map(s => s === 'unknown' ? 'succeeded' : s) })); toast('기존 실행 결과 확인 · 후속 단계는 보류'); }}>기존 결과 다시 확인</Button>}{!['complete', 'cancelled', 'failed'].includes(c.phase) && !c.cancelRequested && <Button disabled={blocked} onClick={() => modify(cancelCommand)}>{c.phase === 'plan' ? '계획 취소' : '미실행 단계 취소'}</Button>}</div>
    </>}
  </Card><div className="stack"><Card title="요청 내용"><p className="request-copy">{c.text}</p><p className="muted request-target">{c.target || '대상 확인 전'}</p></Card><RouteLink to="/owner/monitor">관제 화면</RouteLink></div></div></>;
}
function Cell({ label, children, actions }: { label: string; children: ReactNode; actions?: boolean }) { return <td role="cell" data-label={label} className={actions ? 'cell-actions' : ''}>{children}</td>; }
export function Relationships() {
  const { state, setState, open, blocked } = useApp(); const tabs = [['customers', '고객'], ['vehicles', '차량'], ['links', '연결 정보']] as const;
  const headers = state.tab === 'customers' ? ['고객 별칭', '상태', '관리'] : state.tab === 'vehicles' ? ['차량 별칭', '연결된 고객', '관리'] : ['관측 대상', '연결 대상', '검토 상태', '관리'];
  return <><Head title="등록 정보" action={state.tab !== 'links' && <Button variant="primary" disabled={blocked} onClick={() => open({ type: 'record', kind: state.tab as 'customers' | 'vehicles' })}>{state.tab === 'customers' ? '고객 등록' : '차량 등록'}</Button>}/><div className="filters" role="group" aria-label="등록 정보 종류">{tabs.map(([value, label]) => <button className="filter" key={value} aria-pressed={state.tab === value} onClick={() => setState(s => ({ ...s, tab: value }))}>{label}</button>)}</div><Card body={false}><DataRegion empty="등록 정보 없음"><div className="table-wrap"><table className="relationship-table" role="table"><thead role="rowgroup"><tr role="row">{headers.map(h => <th role="columnheader" scope="col" key={h}>{h}</th>)}</tr></thead><tbody role="rowgroup">{state.tab === 'links' ? state.mappings.map(m => <tr role="row" key={m.object}><Cell label="관측 대상"><strong>{m.object}</strong><small>{m.kind === 'vehicles' ? '관측 차량 ↔ 등록 차량' : '관측 사람 ↔ 고객'}</small></Cell><Cell label="연결 대상">{state[m.kind].find(r => r.id === m.target)?.name || '연결 없음'}</Cell><Cell label="검토 상태"><Badge tone={m.status === '불확실' ? 'amber' : ''}>{m.status}</Badge><small>버전 {m.version} · {m.reason}</small></Cell><Cell label="관리" actions><Button disabled={blocked} onClick={() => open({ type: 'mapping', id: m.object, version: m.version })}>연결 검토</Button></Cell></tr>) : state[state.tab].map(r => <tr role="row" key={r.id}><Cell label={state.tab === 'customers' ? '고객 별칭' : '차량 별칭'}><strong>{r.name}</strong></Cell><Cell label={state.tab === 'customers' ? '상태' : '연결된 고객'}>{state.tab === 'customers' ? <Badge>{r.active}</Badge> : state.customers.find(c => c.id === r.customer)?.name || '연결 없음'}</Cell><Cell label="관리" actions><Button disabled={blocked} onClick={() => open({ type: 'record', kind: state.tab as 'customers' | 'vehicles', id: r.id, version: r.version })}>수정</Button>{state.tab === 'vehicles' && <Button disabled={blocked} onClick={() => open({ type: 'link', id: r.id, version: r.version })}>차주 연결</Button>}</Cell></tr>)}</tbody></table></div></DataRegion></Card></>;
}
function NotificationRow() { const { state } = useApp(); return <a className="list-item clickable" href="#/driver/notifications/move-request"><span className="list-dot"/><span className="list-text"><strong>차량 이동 요청</strong><small>서측 통로 · 14:21</small><Badge tone={state.responses.move ? '' : 'red'}>{state.responses.move || (state.deadlinePassed ? '응답 기한 경과' : '응답 대기')}</Badge></span><span className="list-arrow" aria-hidden="true">↗</span></a>; }
export function DriverVehicle() {
  const { state, setState, open, blocked } = useApp(); const report = state.reports.filter(r => r.vehicle === state.vehicle).at(-1); const observed = state.vehicle === 'car-b';
  const position = driverLocations[state.driverLocation] || driverLocations.bay;
  const lastKnown = ['stale', 'offline'].includes(state.mode);
  const locationHeading = observed && !lastKnown ? position.heading : '마지막 관측 위치';
  const locationValue = !observed ? '관측 위치 확인 전' : lastKnown && state.driverLocation === 'bay' ? `주차면 ${position.value}` : position.value;
  return <><Head title="내 차량"/><div className="grid equal"><Card title="차량 정보"><Field label="차량 선택" as="select" input={{ value: state.vehicle, onChange: e => setState(s => ({ ...s, vehicle: e.target.value })) }}><option value="car-b">내 차량 B</option><option value="car-c">관측 없는 차량 C</option></Field><DataRegion empty="차량 관측 없음"><div className="vehicle-title">{observed ? '내 차량 B' : '차량 C'}</div><div className="vehicle-location"><small>{locationHeading}</small><strong>{locationValue}</strong><span>{observed ? `차량 02 · ${observedAt}` : '위치 없음 · 관측 시각 없음'}</span></div></DataRegion><Button variant="primary full" disabled={blocked} onClick={() => open({ type: 'report' })}>출차 방해 신고</Button>{report && <div className="section-gap"><Notice title="신고 접수 · 검토 대기" neutral>{report.text}</Notice></div>}</Card><div className="stack"><Card title="알림" action={<RouteLink to="/driver/notifications" className="btn-link">전체 보기</RouteLink>} body={false}><DataRegion empty="알림 없음">{observed && canReceive(state.delivery) ? <NotificationRow/> : <Empty title="알림 없음"/>}</DataRegion></Card><Card title="주차장 이용안내" action={<Badge>준비 중</Badge>}><Button variant="full" onClick={() => open({ type: 'guide' })}>질문하기</Button></Card></div></div></>;
}
export function Notifications() { const { state } = useApp(); const received = canReceive(state.delivery); return <><Head title="알림" action={<Badge>{state.mode === 'empty' || !received ? 0 : 1}건</Badge>}/><Card body={false}><DataRegion empty="알림 없음">{received ? <NotificationRow/> : <Empty title="알림 없음"/>}</DataRegion></Card></>; }
export function NotificationDetail({ id }: { id: string }) {
  const { state, setState, blocked, toast } = useApp(); const [saving, setSaving] = useState(false); const [error, setError] = useState(false); const timer = useRef<ReturnType<typeof setTimeout> | null>(null);
  const latest = useRef(state);
  useEffect(() => { latest.current = state; }, [state]);
  useEffect(() => { setSaving(false); return () => { if (timer.current) clearTimeout(timer.current); }; }, [state.delivery, state.mode, state.session?.account]);
  // This component unmounts on logout/revocation; no pending result can re-enter a later session.
  if (id !== 'move-request' || !canReceive(state.delivery)) return <Missing name="알림" to="/driver/notifications"/>;
  const reply = state.responses.move;
  const choose = (value: Reply) => { if (blocked || saving) return; const origin = document.activeElement as HTMLElement; setError(false); setSaving(true); timer.current = setTimeout(() => { setSaving(false); requestAnimationFrame(() => { if (origin.isConnected) origin.focus(); }); if (!canReceive(latest.current.delivery) || ['offline', 'loading', 'error', 'expired', 'revoked'].includes(latest.current.mode) || latest.current.session?.account !== state.session?.account) return; if (latest.current.saveScenario === 'failure') { setError(true); return; } setState(s => s.session?.role === 'driver' ? { ...s, responses: { move: value }, drafts: { ...s.drafts, reply: { value } } } : s); toast('응답 저장 · ' + notificationSummary({ ...latest.current, responses: { move: value } })); }, 450); };
  return <><RouteLink to="/driver/notifications" className="back">알림 목록으로</RouteLink><Head title="차량 이동 요청" action={<Badge tone={reply ? '' : 'red'}>{saving ? '응답 저장 중' : reply ? '응답 저장' : '응답 대기'}</Badge>}/><div className="grid equal"><Card title="내 차량 B · 서측 통로" action={<Icon name="bell"/>}><p>통로 확보를 위해 차량을 안전하게 이동해 주세요.</p><p className="form-note section-gap">응답 후에도 차량 이동 확인이 필요합니다.</p><div className="reply-buttons" role="group" aria-label="차주 응답">{(['확인했어요', '이동할게요', '이동하기 어려워요', '문의할게요'] as Reply[]).map(label => <Button key={label} variant={reply === label ? 'selected' : ''} aria-pressed={reply === label} disabled={blocked || saving} onClick={() => choose(label)}>{label}</Button>)}</div>{error && <Notice title="응답을 저장하지 못했어요."><Button onClick={() => { setState(s => ({ ...s, saveScenario: 'normal' })); setError(false); }}>다시 응답 준비</Button></Notice>}{reply && <Notice title={`내 응답: ${reply}`} neutral>{notificationSummary(state)}</Notice>}<RouteLink to="/driver/vehicle" className="btn full">내 차량</RouteLink></Card><Card title="확인 상태"><Timeline items={[{ title: '알림 전달·수신', text: deliveryLabels[state.delivery] }, { title: '내 응답', text: reply || (state.deadlinePassed ? '응답 기한 경과 · 소유자 확인 필요' : '응답 대기') }, { title: '차량 이동·통로 회복', text: notificationSummary(state), pending: state.followup !== 'recovered' }]}/></Card></div></>;
}
export function Missing({ name, to }: { name: string; to: string }) { return <><Head title={`${name} 없음`}/><RouteLink to={to}>목록으로 돌아가기</RouteLink></>; }
