import { mapCars, observedAt } from './fixtures';
import { Badge, Facts } from './components';
export function ParkingMap({ selected, onSelect, onCase, stale = false }: { selected: string; onSelect: (id: string) => void; onCase: () => void; stale?: boolean }) {
  const activate = (e: React.KeyboardEvent<SVGGElement>, action: () => void) => { if (e.key === 'Enter' || e.key === ' ') { e.preventDefault(); action(); } };
  const car = mapCars.find(c => c.id === selected);
  return <><div className="map-wrap" tabIndex={0} aria-label="주차장 지도"><svg className={`parking-map ${stale ? 'map-stale' : ''}`} viewBox="-12 -12 664 536" role="group" aria-label="가상 주차장 배치. 차량을 선택할 수 있습니다.">
    <rect width="640" height="512" fill="#f1efe9" stroke="#c6c1b7"/>
    <rect y="160" width="128" height="64" fill="#e2dfd8"/><rect x="128" y="128" width="384" height="128" fill="#e2dfd8"/><rect x="448" y="128" width="96" height="320" fill="#e2dfd8"/><rect x="40" width="48" height="160" fill="#e2dfd8"/><rect x="320" y="32" width="64" height="320" fill="#d6dfcc" opacity=".75"/>
    {Array.from({ length: 6 }, (_, i) => <g key={i}><rect x={128 + i * 48} y="48" width="48" height="80" fill={i === 0 ? '#e5e2db' : 'white'} stroke="#c6c1b7"/><text x={152 + i * 48} y="66" textAnchor="middle">B0{i + 1}</text></g>)}
    <path d="M150 192h360M496 260v130" stroke="#aaa69d" strokeDasharray="10 12" fill="none"/>
    <text x="205" y="232">중앙 통로</text><text className="walk-label" x="334" y="333">보행 구역</text><text x="14" y="147">서측 통로</text>
    {mapCars.map(c => <g key={c.id} className="map-car" role="button" tabIndex={0} aria-label={`차량 ${c.id} · ${c.place}`} aria-pressed={selected === c.id} onClick={() => onSelect(c.id)} onKeyDown={e => activate(e, () => onSelect(c.id))}><rect className="car-hit" x={c.x - 9} y={c.y - 4} width="48" height="76" fill="transparent"/>{selected === c.id && <rect x={c.x - 5} y={c.y - 5} width="40" height="78" rx="5" fill="none" stroke="#36788f" strokeWidth="3"/>}<rect x={c.x} y={c.y} width="30" height="68" fill={selected === c.id ? '#36788f' : '#343330'}/><path d={`M${c.x + 6} ${c.y + 8}h18M${c.x + 6} ${c.y + 59}h18`} stroke="#8c8981"/><text className="car-label" x={c.x + 15} y={c.y + 39} textAnchor="middle">{c.id}</text></g>)}
    <circle cx="352" cy="320" r="7" fill="#5d7959"/><circle cx="352" cy="320" r="15" fill="none" stroke="#5d7959" strokeDasharray="3 3"/>
    <rect x="448" y="416" width="48" height="96" fill="#eee9e2"/><rect x="496" y="416" width="48" height="96" fill="#eee9e2"/><path d="M448 464h48M496 464h48" stroke="#7c8777" strokeWidth="4"/><text className="gate-label" x="472" y="494" textAnchor="middle">입구 ↑</text><text className="gate-label" x="520" y="494" textAnchor="middle">출구 ↓</text>
    <g className="map-hotspot" role="button" tabIndex={0} aria-label="서측 통로 사건 상세 보기" onClick={onCase} onKeyDown={e => activate(e, onCase)}><circle className="hotspot-ring" cx="64" cy="196" r="47" fill="none" stroke="#e33320" strokeWidth="2" strokeDasharray="5 5"/><rect x="96" y="265" width="131" height="30" fill="#e33320"/><text x="106" y="285" style={{ fill: '#fff', fontSize: 12 }}>사건 상세 보기 →</text><path d="M97 265 78 239" stroke="#e33320"/></g><text className="map-label" x="24" y="402">40 × 32m</text>
  </svg></div><p className="map-scroll-hint">지도를 좌우로 밀어 확인하세요.</p><div className="map-legend"><span><i className="swatch"/>차량</span><span><i className="swatch walk"/>보행 구역</span><span><i className="swatch red"/>사건 위치</span></div>{car && <div className="card-body map-selection" role="status"><Badge>선택 차량 {car.id}</Badge><Facts items={[[car.name, car.place], ['마지막 관측', observedAt]]}/></div>}</>;
}
